class CreateCompares < ActiveRecord::Migration[5.1]
  def change
    create_table :compares do |t|
	  t.string :home_player_name
	  t.string :home_link
	  t.string :away_full_name
	  t.string :away_link
	  t.string :head_home_player_name
      t.string :head_away_player_name
      t.integer :head_home_player_gp
      t.integer :head_away_player_gp
      t.integer :head_home_player_gs
      t.integer :head_away_player_gs
      t.float :head_home_player_mp
      t.float :head_away_player_mp
      t.float :head_home_player_fg
      t.float :head_away_player_fg
      t.float :head_home_player_fga
      t.float :head_away_player_fga
      t.float :head_home_player_p
      t.float :head_away_player_p
      t.float :head_home_player_pa
      t.float :head_away_player_pa
      t.float :head_home_player_ft
      t.float :head_away_player_ft
      t.float :head_home_player_fta
      t.float :head_away_player_fta
      t.float :head_home_player_orb
      t.float :head_away_player_orb
      t.float :head_home_player_stl
      t.float :head_away_player_stl
      t.float :head_home_player_blk
      t.float :head_away_player_blk
      t.float :head_home_player_tov
      t.float :head_away_player_tov
      t.float :head_home_player_pts
      t.float :head_away_player_pts
      t.string :first_home_player_name
      t.integer :first_home_player_age
      t.integer :first_home_player_gp
      t.integer :first_home_player_gs
      t.float :first_home_player_mp
      t.float :first_home_player_fg
      t.float :first_home_player_fga
      t.float :first_home_player_p
      t.float :first_home_player_pa
      t.float :first_home_player_ft
      t.float :first_home_player_fta
      t.float :first_home_player_orb
      t.float :first_home_player_stl
      t.float :first_home_player_blk
      t.float :first_home_player_tov
      t.float :first_home_player_pts
      t.string :second_home_player_name
      t.integer :second_home_player_age
      t.integer :second_home_player_gp
      t.integer :second_home_player_gs
      t.float :second_home_player_mp
      t.float :second_home_player_fg
      t.float :second_home_player_fga
      t.float :second_home_player_p
      t.float :second_home_player_pa
      t.float :second_home_player_ft
      t.float :second_home_player_fta
      t.float :second_home_player_orb
      t.float :second_home_player_stl
      t.float :second_home_player_blk
      t.float :second_home_player_tov
      t.float :second_home_player_pts
      t.string :first_away_player_name
      t.integer :first_away_player_age
      t.integer :first_away_player_gp
      t.integer :first_away_player_gs
      t.float :first_away_player_mp
      t.float :first_away_player_fg
      t.float :first_away_player_fga
      t.float :first_away_player_p
      t.float :first_away_player_pa
      t.float :first_away_player_ft
      t.float :first_away_player_fta
      t.float :first_away_player_orb
      t.float :first_away_player_stl
      t.float :first_away_player_blk
      t.float :first_away_player_tov
      t.float :first_away_player_pts
      t.string :second_away_player_name
      t.integer :second_away_player_age
      t.integer :second_away_player_gp
      t.integer :second_away_player_gs
      t.float :second_away_player_mp
      t.float :second_away_player_fg
      t.float :second_away_player_fga
      t.float :second_away_player_p
      t.float :second_away_player_pa
      t.float :second_away_player_ft
      t.float :second_away_player_fta
      t.float :second_away_player_orb
      t.float :second_away_player_stl
      t.float :second_away_player_blk
      t.float :second_away_player_tov
      t.float :second_away_player_pts
      t.timestamps
    end
  end
end
