class CreateNbaClones < ActiveRecord::Migration[5.1]
  def change
    create_table :nba_clones do |t|
		t.string :home_team
		t.string :away_team
		t.integer :game_id
		t.string :game_date
		t.string :home_abbr
		t.string :away_abbr
		t.integer :away_last_game
		t.integer :away_next_game
		t.integer :away_first_quarter
		t.integer :away_second_quarter
		t.integer :away_third_quarter
		t.integer :away_forth_quarter
		t.integer :away_ot_quarter
		t.integer :home_last_game
		t.string :home_last_fly
		t.integer :home_next_game
		t.string :home_next_fly
		t.integer :home_first_quarter
		t.integer :home_second_quarter
		t.integer :home_third_quarter
		t.integer :home_forth_quarter
		t.integer :home_ot_quarter
		t.integer :away_score
		t.integer :home_score
		t.integer :total_score
		t.integer :first_point
		t.integer :second_point
		t.integer :total_point
		t.string :year
		t.string :date
		t.integer :home_number
		t.integer :away_number
		t.string :time
		t.string :week
		t.integer :away_mins
		t.integer :away_fga
		t.integer :away_fta
		t.integer :away_toValue
		t.integer :away_orValue
		t.integer :home_mins
		t.integer :home_fga
		t.integer :home_fta
		t.integer :home_toValue
		t.integer :home_orValue
		t.float :first_opener_side
		t.float :first_closer_side
		t.float :first_opener_total
		t.float :first_closer_total
		t.float :second_opener_side
		t.float :second_closer_side
		t.float :second_opener_total
		t.float :second_closer_total
		t.float :full_opener_side
		t.float :full_closer_side
		t.float :full_opener_total
		t.float :full_closer_total
		t.integer :first_away_fga
		t.integer :first_away_fta
		t.integer :first_away_toValue
		t.integer :first_away_orValue
		t.integer :first_home_fga
		t.integer :first_home_fta
		t.integer :first_home_toValue
		t.integer :first_home_orValue
		t.integer :first_away_stl
		t.integer :first_away_blk
		t.integer :first_home_stl
		t.integer :first_home_blk
		t.string :away_last_fly
		t.string :away_next_fly
		t.string :home_last_ot
		t.string :away_last_ot
		t.string :home_timezone
		t.integer :home_win_rank
		t.integer :home_ppg_rank
		t.integer :home_oppppg_rank
		t.string :away_timezone
		t.integer :away_win_rank
		t.integer :away_ppg_rank
		t.integer :away_oppppg_rank
		t.float :pace
		t.float :away_ortg
		t.float :home_ortg
		t.integer :away_last_home
		t.integer :away_next_home
		t.string :pg_away_one_name
		t.integer :pg_away_one_min
		t.string :pg_away_two_name
		t.integer :pg_away_two_min
		t.string :pg_away_three_name
		t.integer :pg_away_three_min
		t.string :pg_home_one_name
		t.integer :pg_home_one_min
		t.string :pg_home_two_name
		t.integer :pg_home_two_min
		t.string :pg_home_three_name
		t.integer :pg_home_three_min
		t.string :away_fg_percent
		t.string :home_fg_percent
		t.float :avg_fg_road
		t.float :avg_fg_home
		t.float :avg_fg_total
		t.float :avg_first_road
		t.float :avg_first_home
		t.float :avg_first_total
		t.float :avg_second_road
		t.float :avg_second_home
		t.float :avg_second_total
		t.integer :avg_count
		t.string :referee_one
		t.integer :referee_one_last
		t.integer :referee_one_next
		t.string :referee_two
		t.integer :referee_two_last
		t.integer :referee_two_next
		t.string :referee_three
		t.integer :referee_three_last
		t.integer :referee_three_next
		t.integer :away_stl
		t.integer :away_blk
		t.integer :home_stl
		t.integer :home_blk
		t.integer :first_away_pf
		t.integer :first_home_pf
		t.integer :away_pf
		t.integer :home_pf

		t.timestamps
    end
  end
end
